description: A clean, secure and responsive website for information on your local tutor
show_downloads: false
google_analytics:
title: Extra Lessons in Alberton
email: riki.lee2@gmail.com
twitter_username: Tikke-Tikke
github_username: HelloBeastie
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
permalink: /:year/:month/:title/
