title: Extra Lessons in Alberton
email: riki.lee2@gmail.com
description: A clean, secure and responsive website for information on your local tutor!
show_downloads: false
google_analytics:
theme:
twitter_username:
github_username:
# Build settings
markdown: kramdown
